from . import salary_offer
from . import salary_offer_otp
from . import hr_recruitment
from . import hr_applicant
from . import res_company
from . import hr_contract_template
from . import hr_job
from . import hr_religion
from . import hr_employee
from . import hr_skill
from . import hr_contract
from . import hr_contract_signature_trail
from . import hr_department
from . import offer_refuse
from . import api_log
from . import whatsapp